name: Run test script

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test_script:
    # The if directive can be used to skip individual steps
    if: false
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Test Script
        run: sh ./bin/test-script.sh

